services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: '${DEV_POSTGRES_DB:-gasprice}'
      POSTGRES_USER: '${DEV_POSTGRES_USER:-gasprice}'
      POSTGRES_PASSWORD: '${DEV_POSTGRES_PASSWORD:-gasprice}'
